# Generated by Django 3.2.4 on 2021-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='item_ordered',
            field=models.CharField(max_length=100, verbose_name='Item Ordered'),
        ),
    ]
