# Generated by Django 3.2.4 on 2021-06-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210621_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Needed By')),
                ('box_size', models.CharField(choices=[('4', '4-pack'), ('6', '6-pack'), ('12', '12-pack')], default='4', max_length=2, verbose_name='Box Size')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
            ],
        ),
    ]
