# Generated by Django 3.2.3 on 2021-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_size',
        ),
        migrations.AddField(
            model_name='box',
            name='box',
            field=models.CharField(choices=[('4', '4-pack'), ('6', '6-pack'), ('12', '12-pack')], default='4', max_length=2, verbose_name='box'),
        ),
    ]
