# Generated by Django 3.2.4 on 2021-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210623_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_ordered',
            field=models.CharField(choices=[('Blu', 'Blueberry Muffin'), ('Ban', 'Banana Nut Muffin'), ('Cra', 'Cranberry Orange Muffin')], default='Blu', max_length=3, verbose_name='Choose Your Muffin!'),
        ),
    ]
