# Generated by Django 3.2.4 on 2021-06-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210623_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pu', 'picked up'), ('re', 'ready for pickup'), ('sc', 'scheduled'), ('ip', 'in progress')], default='pu', max_length=2)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
            ],
        ),
    ]
