# Generated by Django 3.2.4 on 2021-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ordertracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracker',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='ordertracker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordertracker',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='ordertracker',
            name='status',
            field=models.CharField(choices=[('pu', 'picked up'), ('re', 'ready for pickup'), ('sc', 'scheduled'), ('ip', 'in progress')], default='pu', max_length=2, verbose_name='status'),
        ),
    ]
