# Generated by Django 3.2.4 on 2021-06-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_auto_20210624_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertracker',
            name='status',
            field=models.CharField(choices=[('pu', 'picked up'), ('re', 'ready for pickup'), ('sc', 'scheduled'), ('ip', 'in progress')], default='pu', max_length=2, verbose_name='Order Status'),
        ),
    ]
