# Generated by Django 3.2.4 on 2021-06-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_ordertracker_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracker',
            name='order_number',
        ),
    ]
