# Generated by Django 3.2.4 on 2021-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_ordertracker_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pu', 'picked up'), ('re', 'ready for pickup'), ('sc', 'scheduled'), ('ip', 'in progress')], default='pu', max_length=2, verbose_name='Order Status'),
        ),
        migrations.DeleteModel(
            name='OrderTracker',
        ),
    ]
