# Generated by Django 3.2.4 on 2021-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210624_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sc', 'Scheduled'), ('ip', 'In Progress'), ('re', 'Ready For Pickup'), ('pu', 'Picked up')], default='sc', max_length=2, verbose_name='Order Status'),
        ),
    ]
