# Generated by Django 3.2.4 on 2021-06-25 23:16

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_order_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
