# Generated by Django 3.2.4 on 2025-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box',
            field=models.CharField(choices=[('1', 'Single Item'), ('4', '4 Pack'), ('6', '6 Pack'), ('12', '12 Pack')], default='1', max_length=2, verbose_name='box'),
        ),
        migrations.AlterField(
            model_name='box',
            name='item_ordered',
            field=models.CharField(choices=[('BR', 'Bread'), ('DG', 'Dough'), ('CK', 'Cookies'), ('MF', 'Muffins'), ('BS', 'Biscuits'), ('CP', 'Cupcakes'), ('PT', 'Pastries'), ('DN', 'Donut'), ('CR', 'Cream Roll'), ('CB', 'Chess Bars'), ('CH', 'Cheesecake Bars'), ('KP', 'Cake Pops'), ('TC', 'Tea Cakes'), ('CHB', 'shooseberry')], default='BR', max_length=3, verbose_name='Choose Your Muffin!'),
        ),
    ]
