# Generated by Django 3.2.4 on 2025-12-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20251226_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='item_ordered',
            field=models.CharField(choices=[('BR', 'Bread'), ('DG', 'Dough'), ('CK', 'Cookies'), ('MF', 'Muffins'), ('BS', 'Biscuits'), ('CP', 'Cupcakes'), ('PT', 'Pastries'), ('DN', 'Donut'), ('CR', 'Cream Roll'), ('CB', 'Chess Bars'), ('CH', 'Cheesecake Bars'), ('KP', 'Cake Pops'), ('TC', 'Tea Cakes'), ('CHB', 'shooseberry'), ('PT', 'Pattice')], default='BR', max_length=3, verbose_name='Choose Your Muffin!'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
