# Generated by Django 3.2.25 on 2025-12-31 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Name')),
                ('customer_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('sc', 'Scheduled'), ('ip', 'In Progress'), ('re', 'Ready For Pickup'), ('pu', 'Picked up')], default='sc', max_length=2, verbose_name='Order Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Needed By')),
                ('box', models.CharField(choices=[('1', 'Single Item'), ('4', '4 Pack'), ('6', '6 Pack'), ('12', '12 Pack')], default='1', max_length=2, verbose_name='Box Size')),
                ('item_ordered', models.CharField(choices=[('BR', 'Bread'), ('DG', 'Dough'), ('CK', 'Cookies'), ('MF', 'Muffins'), ('BS', 'Biscuits'), ('CP', 'Cupcakes'), ('PT', 'Pastries'), ('DN', 'Donut'), ('CR', 'Cream Roll'), ('CB', 'Chess Bars'), ('CH', 'Cheesecake Bars'), ('KP', 'Cake Pops'), ('TC', 'Tea Cakes'), ('CHB', 'Shooseberry'), ('PT', 'Pattice')], default='BR', max_length=3, verbose_name='Item Selected')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
            ],
        ),
    ]
